# REQUIRED: What's the name of your project?
project_title: My Open Humans Project

# REQUIRED: Will be displayed on the front page of the uploader
project_description: This template demonstrates how you can run your own Open Humans data upload project.

# REQUIRED: Where can we find your project on Open Humans
oh_activity_page: https://www.openhumans.org/activity/your-project-url/

# REQUIRED: which URL will lead to your Open Humans uploader
app_base_url: http://127.0.0.1:5000

# REQUIRED: Tell Open Humans what kind of data is being uploaded
file_description: This is an example file that doesnt have any meaning.

# REQUIRED: Tags to add to your file uploads
file_tags:
- tags
- 'are a good way to'
- 'describe the files you are uploading'

# Give the path to the logo of your project.
logo: ' static/example_logo.png'

# Is there a larger project website where more info might be located?
more_info_link: http://www.github.com/gedankenstuecke/oh_data_uploader
